### ISSUE TITLE
静的解析の自動化

### ISSUE THREAD

**Issue by DaigoWakabayashi** [DaigoWakabayashi/NyanBuzz#20]
## やること

- 静的解析の自動化
- CI時に静的解析を走らせる
- 全クリしないとマージできない制御をかける

## 参考

- https://qiita.com/tokkun5552/items/2eb6793501c152dabf33

**Comment by DaigoWakabayashi** [comment]
今日はコレやろう

**Comment by DaigoWakabayashi** [comment]
お、flutter analyze が走ってる
けど、長くないか

![CleanShot 2022-03-15 at 21 40 53](https://user-images.githubusercontent.com/65471734/158379798-c8574d26-0f61-44ca-af41-5512cd262fb4.png)

**Comment by DaigoWakabayashi** [comment]
お、コケた
恐ろしいくらいの issue 見つかってて :くさ:

![CleanShot 2022-03-15 at 21 43 08](https://user-images.githubusercontent.com/65471734/158380163-3b39d611-5219-45ee-83c6-5b44283d8b5b.png)

**Comment by DaigoWakabayashi** [comment]
ローカルで `flutter analyze` 走らせてみた
generated なんたらは Ignore してるので大丈夫そうだし、上記の issue 数からして別問題の可能性高い

![CleanShot 2022-03-15 at 21 44 29](https://user-images.githubusercontent.com/65471734/158380371-4b880f08-7e67-41f2-8d40-e306836d1b41.png)

**Comment by DaigoWakabayashi** [comment]
なんかログ見る限り flutter とかパッケージの内部まで pedantic_mono で analyze しちゃってる気がする

**Comment by DaigoWakabayashi** [comment]
`flutter analyze --current-package` でこのプロジェクトのコードだけ解析してくれるらしいけど、デフォルトでONになってるハズなんだよな〜

![CleanShot 2022-03-15 at 22 00 03](https://user-images.githubusercontent.com/65471734/158383008-8d3825c4-b9b2-4c04-a393-aaebb85999af.png)

**Comment by DaigoWakabayashi** [comment]
お、チャンネル指定できてないの怪しいかも？

![CleanShot 2022-03-15 at 22 07 34](https://user-images.githubusercontent.com/65471734/158384426-81515a7a-969a-409d-81e5-01ce86e8479c.png)

**Comment by DaigoWakabayashi** [comment]
この記事参考になるな〜
job ごとに flutter をインストールするようにしないといけないっぽい

https://qiita.com/sensuikan1973/items/cf4626f480cb584a9e50

**Comment by DaigoWakabayashi** [comment]
stable にならんかった

![CleanShot 2022-03-15 at 22 15 13](https://user-images.githubusercontent.com/65471734/158385670-a7c6046d-a97e-4262-ba6f-3d37ed836607.png)

**Comment by tokku5552** [comment]
> なんかログ見る限り flutter とかパッケージの内部まで pedantic_mono で analyze しちゃってる気がする

これcouple todoでも同じ問題が起きて、そのときはpedantic_monoを普通のpedanticにしてanalysis.yamlをインポートするんじゃなくて直書きすることで回避しました。

そもそもローカルでflutter analyze通ります？

**Comment by DaigoWakabayashi** [comment]
> そもそもローカルでflutter analyze通ります？

ローカルでは通りますね！
https://github.com/DaigoWakabayashi/NyanBuzz/issues/20#issuecomment-1067947452

**Comment by tokku5552** [comment]
3issueなんで多分だめじゃないかなと思います。  
あとfvm経由でやってるので、今対応してるようですが、flutterのバージョンもあってなさそうですね 🤔

**Comment by DaigoWakabayashi** [comment]
> これcouple todoでも同じ問題が起きて、そのときはpedantic_monoを普通のpedanticにしてanalysis.yamlをインポートするんじゃなくて直書きすることで回避しました。

なるほど
include じゃなくて直書きするんですね！
https://github.com/flutteruniv/couple_todo/blob/main/analysis_options.yaml

**Comment by DaigoWakabayashi** [comment]
お、flutter のインストール方法変えたら ローカルと同じ結果になった

![CleanShot 2022-03-15 at 22 26 06](https://user-images.githubusercontent.com/65471734/158387576-c330ca2c-7dd4-4259-a7cc-936ec6900e9a.png)

**Comment by DaigoWakabayashi** [comment]
この generated なんたらって Ignore しても pub get かなんかの時に生成されるんだな
analyzer の対象外にしたらイケるかも

**Comment by DaigoWakabayashi** [comment]
generated なんたらは、web のビルドに必要なファイルらしい
flutter config --no-enable-web で生成されなくなった
https://stackoverflow.com/questions/65356481/why-this-file-automatically-creates-itself-generated-plugin-registrant-dart

**Comment by DaigoWakabayashi** [comment]
ローカルで通った

![CleanShot 2022-03-15 at 22 32 55](https://user-images.githubusercontent.com/65471734/158389215-5efe101d-d955-4308-9d58-206c8f064261.png)

**Comment by DaigoWakabayashi** [comment]
これで通ってもらわんとダイゴは困る

![CleanShot 2022-03-15 at 22 38 13](https://user-images.githubusercontent.com/65471734/158389912-bf06cf0f-08f2-4f16-84e2-1e07d2d5e731.png)

**Comment by DaigoWakabayashi** [comment]
:キモチエェェ:

![CleanShot 2022-03-15 at 22 39 33](https://user-images.githubusercontent.com/65471734/158390140-e3bf5b28-a75f-4660-987c-f41c894b6a8d.png)

**Comment by DaigoWakabayashi** [comment]
果たして pedantic_mono が適用されているのか気になる
アラート出したままプッシュしてみよう

**Comment by DaigoWakabayashi** [comment]
> 果たして pedantic_mono が適用されているのか気になる
> アラート出したままプッシュしてみよう

ちゃんと効いてた

![CleanShot 2022-03-15 at 22 45 22](https://user-images.githubusercontent.com/65471734/158391258-4667b274-e20f-47de-81e3-729fcd41ba66.png)

**Comment by DaigoWakabayashi** [comment]
一旦休憩
カバレッジ可視化もやってみよ

**Comment by DaigoWakabayashi** [comment]
23時やん
issue 切り分けて明日やろう

**Comment by DaigoWakabayashi** [comment]
https://github.com/DaigoWakabayashi/NyanBuzz/issues/24
こちらで実装する

**Comment by DaigoWakabayashi** [comment]
@tokku5552 

以下の対応で通るようになりました！
flutter のインストール時にチャンネルを指定するようにすると https://github.com/DaigoWakabayashi/NyanBuzz/issues/20#issuecomment-1067953010 の問題が出なくなった感じです！
助言頂きありがとうございました！！

  - flutter のインストール方法を [スクリプト](https://zenn.dev/k9i/articles/65ed8841d5e3ff)から[ Acitons のパッケージ?](https://github.com/subosito/flutter-action)に変更
  - flutter config --no-enable-web のワークフローを追加（ generated_plugin ... ファイルが生成されて解析でコケるので）

**Comment by tokku5552** [comment]
なるほど、`flutter config --no-enable-web `これでちゃんとpassさせるのが正しい対処っぽいですね！流石です！
