### ISSUE TITLE
Codecovでカバレッジの可視化

### ISSUE THREAD

**Issue by DaigoWakabayashi** [DaigoWakabayashi/NyanBuzz#24]
## やること

- Codecovでカバレッジの可視化

## 参考

- https://qiita.com/tokkun5552/items/2eb6793501c152dabf33#codecov%E3%81%A7%E3%82%AB%E3%83%90%E3%83%AC%E3%83%83%E3%82%B8%E5%8F%AF%E8%A6%96%E5%8C%96

**Comment by DaigoWakabayashi** [comment]
福岡行ったらなんもやらなそうなのでやっとこ

**Comment by DaigoWakabayashi** [comment]
サインアップして Secrets 追加DONE

![CleanShot 2022-03-16 at 20 20 22](https://user-images.githubusercontent.com/65471734/158578803-bc9445f4-f9d6-49ac-a0e9-910a7de0db7e.png)

**Comment by DaigoWakabayashi** [comment]
どうなるだろうか

![CleanShot 2022-03-16 at 20 27 17](https://user-images.githubusercontent.com/65471734/158579983-03b5a879-a9c6-4e6b-98a2-accb0add52f6.png)

**Comment by DaigoWakabayashi** [comment]
おお〜ローカル実行も出来た


https://qiita.com/tokkun5552/items/2eb6793501c152dabf33#mac%E3%81%A7%E3%81%82%E3%82%8C%E3%81%B0%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E3%81%A7%E3%82%82%E5%8F%AF%E8%A6%96%E5%8C%96%E3%81%A7%E3%81%8D%E3%82%8B

![CleanShot 2022-03-16 at 20 30 21](https://user-images.githubusercontent.com/65471734/158580529-f6cec3b5-8ae0-4a86-b1de-6c11bc833be2.png)

**Comment by DaigoWakabayashi** [comment]
出てた、お手軽だな

![CleanShot 2022-03-16 at 20 34 22](https://user-images.githubusercontent.com/65471734/158581204-ec1685ce-fce3-4bf3-a435-5eb6ab81b455.png)
![CleanShot 2022-03-16 at 20 34 11](https://user-images.githubusercontent.com/65471734/158581210-fcb502f5-af84-4e6a-9d27-0c6be8d196a6.png)

**Comment by DaigoWakabayashi** [comment]
bot User を勧められてる
これ プルリク上でコメントとかくれるヤツかな
やってみよ

**Comment by DaigoWakabayashi** [comment]
カバレッジの意味ついてちょっと調べてみる

- カバレッジ(網羅率)分析とは

> カバレッジとは、取材範囲、補償範囲、受信範囲、対象範囲、被覆率などの意味を持つ英単語。カバーする範囲、カバー率の意。

うん

> ソフトウェア開発において、出来上がったプログラムのテストをする際に、どの程度をテスト対象とする（ことができる）かをカバレッジ（テストカバレッジ）という。範囲の定義の仕方によりいくつかの種類があり、命令全体のうちテストできるものの比率を「[ステートメントカバレッジ](https://e-words.jp/w/%E5%91%BD%E4%BB%A4%E7%B6%B2%E7%BE%85.html)」（命令網羅率）、コード内の分岐のうちテストできるものの比率を「[ブランチカバレッジ](https://e-words.jp/w/%E5%88%86%E5%B2%90%E7%B6%B2%E7%BE%85.html)」（分岐網羅率）、コード内に記述された条件のうちテストできるものの比率を「[コンディションカバレッジ](https://e-words.jp/w/%E6%9D%A1%E4%BB%B6%E7%B6%B2%E7%BE%85.html)」（条件網羅率）、とそれぞれ呼ぶ。

全コード内のうち、テスト対象になってる割合ってことかな

**Comment by DaigoWakabayashi** [comment]
え、まって couple_todo のカバレッジ 90％ 超えってすごくないか

![CleanShot 2022-03-16 at 21 02 21](https://user-images.githubusercontent.com/65471734/158585675-cce3c69e-c3ea-4522-bc8f-09dbe61eec8d.png)

**Comment by DaigoWakabayashi** [comment]
今のニャンバズは、全コードのうち 88％ がテストできてるってことか
カウンターアプリ状態の以下のテストコードで、残りの 12% はなんなんやろ


![CleanShot 2022-03-16 at 21 06 22](https://user-images.githubusercontent.com/65471734/158586349-d078bee1-d3bc-44e6-9faa-ca9a4e8488c2.png)

**Comment by DaigoWakabayashi** [comment]
あ、勉強会だ

**Comment by tokku5552** [comment]
> カウンターアプリ状態の以下のテストコードで、残りの 12% はなんなんやろ

カバレッジ可視化しているならどこのテストが通ってないか見れるはずです！
カバレッジ90%越えといってもいわゆる分岐網羅しか見ていないので、例えば正規表現とかでバリデーションしてたり日付のテストとかだと、その辺を重点的にケース増やす必要があるでしょうね(条件網羅を目指して)

**Comment by DaigoWakabayashi** [comment]
> カバレッジ可視化しているならどこのテストが通ってないか見れるはずです！
> カバレッジ90%越えといってもいわゆる分岐網羅しか見ていないので、例えば正規表現とかでバリデーションしてたり日付のテストとかだと、その辺を重点的にケース増やす必要があるでしょうね(条件網羅を目指して)

見れました！
今見たら自分の Flavor テストコードが Cover できてないみたいですね！
納得しました、ありがとうございます！！


![CleanShot 2022-03-16 at 23 07 22](https://user-images.githubusercontent.com/65471734/158608467-837519dc-fe55-44a0-95cb-b7ec2658a4a2.png)

**Comment by DaigoWakabayashi** [comment]
1h  close

![CleanShot 2022-03-16 at 23 12 24](https://user-images.githubusercontent.com/65471734/158609412-fa4da34b-1f30-4912-b495-1c16fcefcf2d.png)
