### ISSUE TITLE
CI / CD の構築

### ISSUE THREAD

**Issue by DaigoWakabayashi** [DaigoWakabayashi/NyanBuzz#4]
## やること
- CI / CD の構築
- どうせなら Public リポジトリなので GitHub Actions 使いたい

## 参考

- [【Flutter】GitHubActionsでテストと静的解析を自動化する](https://qiita.com/tokkun5552/items/2eb6793501c152dabf33)
- https://zenn.dev/k9i/articles/65ed8841d5e3ff

**Comment by tokku5552** [comment]
これってテストとデプロイ両方自動化したい感じですか？

**Comment by DaigoWakabayashi** [comment]
うおおお徳田さんコメントありがとうございます！

> これってテストとデプロイ両方自動化したい感じですか？

それが理想ですね！
でも CI でテスト組み込んだことない（なんならテストコードもほとんど書いたことない）ので、あまりに沼るようであればデプロイだけやろうかなという感じです！

**Comment by tokku5552** [comment]
なるほど 🤔 
逆にテストのみならやろうかなと思いましたがどうですか？デプロイ側はダイゴさんが書く感じで

**Comment by DaigoWakabayashi** [comment]
うおおああ良いんですか！ぜひお願いしたいです！！
勉強がてらチャレンジするつもりでしたが、せっかく徳田さんがやってくださるならお任せして、それ参考にまた別のタイミングで勉強しようと思います！！

**Comment by DaigoWakabayashi** [comment]
CI 走った〜！！

![CleanShot 2022-03-12 at 20 51 27](https://user-images.githubusercontent.com/65471734/158016904-8615458f-061f-494f-9e1a-591684aed15d.png)

**Comment by DaigoWakabayashi** [comment]
やってくか〜

**Comment by DaigoWakabayashi** [comment]
これ issue 分割した方が良さそうだな
- 静的解析の自動化
- iOS （AppStoreConnect)へのデプロイ
- Android（GooglePlayConsole)へのデプロイ

**Comment by DaigoWakabayashi** [comment]
> * 静的解析の自動化
> * iOS （AppStoreConnect)へのデプロイ
> * Android（GooglePlayConsole)へのデプロイ



- #20 
- #21 
- #22 

タスク化done
この issue は close
